// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The developed-country catalogue. Sweden (`se.ts`) and the United States
// (`us.ts`) are hand-written reference implementations; the rest of the top
// developed countries live here as data rows, each assembled by `defineCountry`
// from the shared grouping kit (`common.ts`). This is deliberately a table, not
// thirty near-identical files: a country's convention is a grouper + a postal
// rule + its identity, and expressing that as data keeps the whole set legible
// and the diff for "add another country" a single row.
//
// The groupings are each country's common written form (French pairs, a NANP
// Canadian number, a Japanese `090-1234-5678`), applied to the national
// significant digits — see `common.ts` for how the trunk `0` and `+cc` prefix
// are wrapped around them. They are display conventions, not the full national
// numbering plan, exactly as Sweden's and the US's headline forms are.

import {
  defineCountry,
  pattern,
  pairs,
  triples,
  nanp,
  plainPostal,
  spacedPostal,
  hyphenPostal,
  alnumAfter,
  alnumTail,
  type PhoneGrouper,
} from "./common.ts";
import type { CountryFormat } from "./types.ts";

// Norway has no trunk 0: an eight-digit number, mobile (4x/9x) grouped 3-2-3
// and everything else in even pairs.
const noGroup: PhoneGrouper = (n) =>
  /^[49]/.test(n) ? pattern([3, 2])(n) : pairs(n);

/** The developed countries beyond the two hand-written references, in no
 *  particular order — the picker sorts them by localised name. */
export const CATALOG: readonly CountryFormat[] = [
  defineCountry({
    code: "NO",
    callingCode: "47",
    flag: "🇳🇴",
    nameKey: "no",
    samples: { phone: "+4795123456", postal: "0150" },
    group: noGroup,
    postal: plainPostal(4),
  }),
  defineCountry({
    code: "DK",
    callingCode: "45",
    flag: "🇩🇰",
    nameKey: "dk",
    samples: { phone: "+4520123456", postal: "1050" },
    group: pairs,
    postal: plainPostal(4),
  }),
  defineCountry({
    code: "FI",
    callingCode: "358",
    flag: "🇫🇮",
    nameKey: "fi",
    samples: { phone: "+358401234567", postal: "00100" },
    trunk: true,
    // Area code, then the subscriber part as one block: 040 1234567.
    group: pattern([2], 99),
    postal: plainPostal(5),
  }),
  defineCountry({
    code: "IS",
    callingCode: "354",
    flag: "🇮🇸",
    nameKey: "is",
    samples: { phone: "+3545611234", postal: "101" },
    group: pattern([3], 4),
    postal: plainPostal(3),
  }),
  defineCountry({
    code: "DE",
    callingCode: "49",
    flag: "🇩🇪",
    nameKey: "de",
    samples: { phone: "+4915112345678", postal: "10115" },
    trunk: true,
    group: triples,
    postal: plainPostal(5),
  }),
  defineCountry({
    code: "GB",
    callingCode: "44",
    flag: "🇬🇧",
    nameKey: "gb",
    samples: { phone: "+447911123456", postal: "SW1A1AA" },
    trunk: true,
    group: pattern([4]),
    postal: alnumTail(3),
  }),
  defineCountry({
    code: "IE",
    callingCode: "353",
    flag: "🇮🇪",
    nameKey: "ie",
    samples: { phone: "+353851234567", postal: "D02AF30" },
    trunk: true,
    group: pattern([2, 3], 4),
    postal: alnumAfter(3),
  }),
  defineCountry({
    code: "FR",
    callingCode: "33",
    flag: "🇫🇷",
    nameKey: "fr",
    samples: { phone: "+33612345678", postal: "75008" },
    trunk: true,
    // The 0 is part of the pairing: 06 12 34 56 78.
    group: pattern([1], 2),
    postal: plainPostal(5),
  }),
  defineCountry({
    code: "NL",
    callingCode: "31",
    flag: "🇳🇱",
    nameKey: "nl",
    samples: { phone: "+31612345678", postal: "1012AB" },
    trunk: true,
    group: pattern([1], 4),
    postal: alnumAfter(4),
  }),
  defineCountry({
    code: "BE",
    callingCode: "32",
    flag: "🇧🇪",
    nameKey: "be",
    samples: { phone: "+32470123456", postal: "1000" },
    trunk: true,
    group: pattern([3], 2),
    postal: plainPostal(4),
  }),
  defineCountry({
    code: "CH",
    callingCode: "41",
    flag: "🇨🇭",
    nameKey: "ch",
    samples: { phone: "+41791234567", postal: "8001" },
    trunk: true,
    group: pattern([2, 3], 2),
    postal: plainPostal(4),
  }),
  defineCountry({
    code: "AT",
    callingCode: "43",
    flag: "🇦🇹",
    nameKey: "at",
    samples: { phone: "+436641234567", postal: "1010" },
    trunk: true,
    group: pattern([3], 4),
    postal: plainPostal(4),
  }),
  defineCountry({
    code: "IT",
    callingCode: "39",
    flag: "🇮🇹",
    nameKey: "it",
    // Italy keeps its leading 0 (no trunk), so numbers group as they stand.
    samples: { phone: "+393123456789", postal: "00100" },
    group: pattern([3, 3], 4),
    postal: plainPostal(5),
  }),
  defineCountry({
    code: "ES",
    callingCode: "34",
    flag: "🇪🇸",
    nameKey: "es",
    samples: { phone: "+34612345678", postal: "28001" },
    group: pattern([3], 2),
    postal: plainPostal(5),
  }),
  defineCountry({
    code: "PT",
    callingCode: "351",
    flag: "🇵🇹",
    nameKey: "pt",
    samples: { phone: "+351912345678", postal: "1000100" },
    group: triples,
    postal: hyphenPostal(7, 4),
  }),
  defineCountry({
    code: "LU",
    callingCode: "352",
    flag: "🇱🇺",
    nameKey: "lu",
    samples: { phone: "+352621123456", postal: "1009" },
    group: triples,
    postal: plainPostal(4),
  }),
  defineCountry({
    code: "CA",
    callingCode: "1",
    flag: "🇨🇦",
    nameKey: "ca",
    samples: { phone: "+14165550123", postal: "K1A0B1" },
    group: nanp,
    postal: alnumAfter(3),
  }),
  defineCountry({
    code: "AU",
    callingCode: "61",
    flag: "🇦🇺",
    nameKey: "au",
    samples: { phone: "+61412345678", postal: "2000" },
    trunk: true,
    group: pattern([3], 3),
    postal: plainPostal(4),
  }),
  defineCountry({
    code: "NZ",
    callingCode: "64",
    flag: "🇳🇿",
    nameKey: "nz",
    samples: { phone: "+6421123456", postal: "6011" },
    trunk: true,
    group: pattern([2], 3),
    postal: plainPostal(4),
  }),
  defineCountry({
    code: "JP",
    callingCode: "81",
    flag: "🇯🇵",
    nameKey: "jp",
    samples: { phone: "+819012345678", postal: "1000001" },
    trunk: true,
    group: pattern([2, 4], 4),
    postal: hyphenPostal(7, 3),
  }),
  defineCountry({
    code: "KR",
    callingCode: "82",
    flag: "🇰🇷",
    nameKey: "kr",
    samples: { phone: "+821012345678", postal: "03187" },
    trunk: true,
    group: pattern([2, 4], 4),
    postal: plainPostal(5),
  }),
  defineCountry({
    code: "SG",
    callingCode: "65",
    flag: "🇸🇬",
    nameKey: "sg",
    samples: { phone: "+6561234567", postal: "018956" },
    group: pattern([4], 4),
    postal: plainPostal(6),
  }),
  defineCountry({
    code: "CZ",
    callingCode: "420",
    flag: "🇨🇿",
    nameKey: "cz",
    samples: { phone: "+420601123456", postal: "11000" },
    group: triples,
    postal: spacedPostal(5, 3),
  }),
  defineCountry({
    code: "PL",
    callingCode: "48",
    flag: "🇵🇱",
    nameKey: "pl",
    samples: { phone: "+48512345678", postal: "00950" },
    group: triples,
    postal: hyphenPostal(5, 2),
  }),
  defineCountry({
    code: "SI",
    callingCode: "386",
    flag: "🇸🇮",
    nameKey: "si",
    samples: { phone: "+38631123456", postal: "1000" },
    trunk: true,
    group: pattern([2], 3),
    postal: plainPostal(4),
  }),
  defineCountry({
    code: "EE",
    callingCode: "372",
    flag: "🇪🇪",
    nameKey: "ee",
    samples: { phone: "+37251234567", postal: "10111" },
    group: pattern([4], 4),
    postal: plainPostal(5),
  }),
  defineCountry({
    code: "IL",
    callingCode: "972",
    flag: "🇮🇱",
    nameKey: "il",
    samples: { phone: "+972501234567", postal: "9490000" },
    trunk: true,
    group: pattern([2, 3], 4),
    postal: plainPostal(7),
  }),
  defineCountry({
    code: "GR",
    callingCode: "30",
    flag: "🇬🇷",
    nameKey: "gr",
    samples: { phone: "+306912345678", postal: "10431" },
    group: pattern([3, 3], 4),
    postal: spacedPostal(5, 3),
  }),
];
