// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The personal half of the demo address book: family, in-laws, friends, the
// loose acquaintances at the menu root, and a few realistically archived
// cards. Part of the "Demo data" roster — see `demoData.ts` for the story
// (whose address book this is) and `demoSpec.ts` for the authoring shape.
//
// Everything here is fictional but deliberately unremarkable: plausible names,
// drama-range phone numbers, RFC 2606 `example` mail domains — the polished,
// lived-in address book of someone who keeps their contacts in order.

import type { DemoContactSpec } from "./demoSpec.ts";

/** Family — the owner's own side, plus the shared household cards. */
export const DEMO_FAMILY: DemoContactSpec[] = [
  // The partner: the fullest card in the book, ICE-flagged and favorite #1.
  {
    slug: "sara",
    first: "Sara",
    last: "Eklund",
    company: "Klarvik Systems AB",
    phones: [
      ["+46 70 555 12 34", "private", "primary"],
      ["+46 8 555 016 20", "work"],
    ],
    emails: [
      ["sara.eklund@example.com", "private"],
      ["sara.eklund@klarvik.example", "work"],
    ],
    addresses: [
      {
        label: "Home",
        street: "Björkallén 7",
        zip: "182 47",
        city: "Enebyberg",
      },
    ],
    birthday: "1987-04-12",
    dates: [
      ["Wedding anniversary", "2014-06-14"],
      ["Name day", "07-19"],
    ],
    notes: "Wife. Work phone only weekdays 9–17.",
    folder: "family",
    glyph: "heart",
    color: "#fca5a5",
    ice: true,
    favorite: 1,
  },
  {
    slug: "elsa",
    first: "Elsa",
    last: "Eklund",
    phones: [["+46 73 555 48 12", "private", "primary"]],
    emails: [["elsa.eklund@example.com", "private"]],
    birthday: "2012-05-11",
    notes: "Our Elsa. School phone — silent during class hours.",
    folder: "family",
    favorite: 7,
  },
  {
    slug: "gunilla",
    first: "Gunilla",
    last: "Sandell",
    phones: [
      ["+46 70 555 21 48", "private", "primary"],
      ["+46 18 555 032 11", "private"],
    ],
    emails: [["gunilla.sandell@example.com", "private"]],
    addresses: [
      { label: "Home", street: "Kvarnvägen 3", zip: "753 29", city: "Uppsala" },
    ],
    birthday: "1956-09-02",
    notes: "Mum. Calls every Sunday evening. Lactose intolerant.",
    folder: "family",
    favorite: 2,
  },
  {
    slug: "lars-erik",
    first: "Lars-Erik",
    last: "Sandell",
    phones: [["+46 70 555 21 47", "private", "primary"]],
    emails: [["lars.erik.sandell@example.com", "private"]],
    addresses: [
      { label: "Home", street: "Kvarnvägen 3", zip: "753 29", city: "Uppsala" },
    ],
    birthday: "1953-01-27",
    dates: [["Name day", "05-18"]],
    notes: "Dad. Retired — out in the boat most days after May.",
    folder: "family",
  },
  // The brother: the second ICE card.
  {
    slug: "henrik",
    first: "Henrik",
    last: "Sandell",
    company: "Vestkust Marin AB",
    phones: [
      ["+46 72 555 90 31", "private", "primary"],
      ["+46 31 555 072 40", "work"],
    ],
    emails: [
      ["henrik.sandell@example.com", "private"],
      ["henrik@vestkustmarin.example", "work"],
    ],
    addresses: [
      {
        label: "Home",
        street: "Ekedalsgatan 21",
        zip: "414 66",
        city: "Göteborg",
      },
    ],
    birthday: "1982-11-08",
    dates: [["Name day", "01-19"]],
    notes: "Little brother. Knows where the summer-house spare key is.",
    folder: "family",
    ice: true,
    favorite: 5,
  },
  {
    slug: "emma",
    first: "Emma",
    last: "Sandell",
    phones: [["+46 73 555 90 32", "private"]],
    emails: [["emma.sandell@example.com", "private"]],
    birthday: "1984-06-23",
    notes: "Henrik's wife. Physiotherapist — good with running injuries.",
    folder: "family",
  },
  {
    slug: "karin",
    first: "Karin",
    last: "Blomqvist",
    phones: [["+46 70 555 64 20", "private", "primary"]],
    emails: [["karin.blomqvist@example.com", "private"]],
    addresses: [
      {
        label: "Home",
        street: "Trastvägen 12",
        zip: "191 44",
        city: "Sollentuna",
      },
    ],
    birthday: "1979-05-30",
    dates: [["Name day", "08-02"]],
    notes: "Big sister. Hosts Christmas Eve on odd years.",
    folder: "family",
  },
  {
    slug: "peter",
    first: "Peter",
    last: "Blomqvist",
    phones: [["+46 70 555 64 21", "private"]],
    emails: [["peter.blomqvist@example.com", "private"]],
    birthday: "1977-10-14",
    notes: "Karin's husband. Ask him about anything with an engine.",
    folder: "family",
  },
  {
    slug: "alva",
    first: "Alva",
    last: "Blomqvist",
    phones: [["+46 76 555 64 22", "private"]],
    birthday: "2008-08-19",
    notes: "Karin's eldest. Starting upper secondary autumn 2024.",
    folder: "family",
  },
  // Grandma: landline only, no email — some cards are realistically sparse.
  {
    slug: "astrid",
    first: "Astrid",
    last: "Sandell",
    phones: [["+46 18 555 044 90", "private"]],
    addresses: [
      {
        label: "Björkbacken care home",
        street: "Solhemsvägen 8, room 214",
        zip: "754 40",
        city: "Uppsala",
      },
    ],
    birthday: "1931-03-03",
    dates: [["Name day", "11-27"]],
    notes: "Grandma. Best time to call is after lunch. No mobile.",
    folder: "family",
    glyph: "home",
    color: "#c4b5fd",
  },
  {
    slug: "bengt",
    first: "Bengt",
    last: "Sandell",
    phones: [["+46 70 555 33 18", "private"]],
    emails: [["bengt.sandell@example.com", "private"]],
    birthday: "1958-07-02",
    notes: "Dad's brother. Hosts midsummer at the farm in Alunda.",
    folder: "family",
  },
  {
    slug: "marianne",
    first: "Marianne",
    last: "Sandell",
    phones: [["+46 70 555 33 19", "private"]],
    birthday: "1960-12-05",
    notes: "Bengt's wife. Makes the midsummer strawberry cake.",
    folder: "family",
  },
  {
    slug: "jonas",
    first: "Jonas",
    last: "Sandell",
    phones: [["+46 72 555 77 05", "private"]],
    emails: [["jonas.sandell@example.com", "private"]],
    addresses: [{ label: "Home", city: "Malmö" }],
    birthday: "1985-02-17",
    notes: "Cousin. Moved to Malmö 2021 — couch to crash on.",
    folder: "family",
  },
];

/** In-laws — Sara's side, filed in a subfolder under Family. */
export const DEMO_INLAWS: DemoContactSpec[] = [
  {
    slug: "ingrid",
    first: "Ingrid",
    last: "Eklund",
    phones: [
      ["+46 70 555 58 03", "private", "primary"],
      ["+46 21 555 018 44", "private"],
    ],
    emails: [["ingrid.eklund@example.com", "private"]],
    addresses: [
      {
        label: "Home",
        street: "Ängsgatan 15",
        zip: "722 18",
        city: "Västerås",
      },
    ],
    birthday: "1958-03-29",
    notes: "Sara's mum. Remembers everyone's birthdays before we do.",
    folder: "inlaws",
  },
  {
    slug: "sven",
    first: "Sven",
    last: "Eklund",
    phones: [["+46 70 555 58 04", "private"]],
    addresses: [
      {
        label: "Home",
        street: "Ängsgatan 15",
        zip: "722 18",
        city: "Västerås",
      },
    ],
    birthday: "1955-08-16",
    notes: "Sara's dad. Chess by post, the old-fashioned way.",
    folder: "inlaws",
  },
  {
    slug: "johan",
    first: "Johan",
    last: "Eklund",
    phones: [["+46 73 555 58 05", "private"]],
    emails: [["johan.eklund@example.com", "private"]],
    birthday: "1990-01-31",
    notes: "Sara's brother. Borrowed the trailer May 2026 — returned.",
    folder: "inlaws",
  },
];

/** Friends — the standing dinner-party crowd plus friends abroad. */
export const DEMO_FRIENDS: DemoContactSpec[] = [
  // The best friend: favorite, multiple ways to reach him.
  {
    slug: "markus",
    first: "Markus",
    last: "Öberg",
    company: "Öberg Foto AB",
    homepage: "https://www.obergfoto.example",
    phones: [
      ["+46 70 555 24 68", "private", "primary"],
      ["+46 8 555 024 70", "work"],
    ],
    emails: [
      ["markus.oberg@example.com", "private"],
      ["markus@obergfoto.example", "work"],
    ],
    addresses: [
      {
        label: "Home",
        street: "Rindögatan 42",
        zip: "115 36",
        city: "Stockholm",
      },
    ],
    birthday: "1983-07-21",
    dates: [["Name day", "04-25"]],
    notes: "Best man at our wedding. Thursday padel, 19:00.",
    folder: "friends",
    favorite: 3,
  },
  {
    slug: "jenny",
    first: "Jenny",
    last: "Öberg",
    phones: [["+46 73 555 24 69", "private"]],
    emails: [["jenny.oberg@example.com", "private"]],
    birthday: "1985-09-14",
    notes: "Markus's wife. Book tips — she reads everything first.",
    folder: "friends",
  },
  {
    slug: "david",
    first: "David",
    last: "Chen",
    company: "Fogline Inc.",
    phones: [["+1 (415) 555-0137", "private", "primary"]],
    emails: [["david.chen@example.com", "private"]],
    addresses: [
      {
        label: "Home",
        street: "2130 Fulton St, Apt 4",
        zip: "94117",
        city: "San Francisco",
      },
    ],
    birthday: "1984-03-08",
    dates: [["Moved to San Francisco", "2016-02-01"]],
    notes: "Uni exchange roommate. Standing sofa offer in the Bay Area.",
    folder: "friends",
  },
  {
    slug: "claire",
    first: "Claire",
    last: "Dubois",
    phones: [["+33 1 99 00 45 21", "private"]],
    emails: [["claire.dubois@example.com", "private"]],
    addresses: [{ label: "Home", city: "Lyon" }],
    birthday: "1986-11-30",
    notes: "Interrail 2007. Visits Stockholm every other summer.",
    folder: "friends",
  },
  {
    slug: "tom",
    first: "Tom",
    last: "Hartley",
    phones: [["+44 20 7946 0810", "private"]],
    emails: [["tom.hartley@example.com", "private"]],
    addresses: [
      {
        label: "Home",
        street: "14 Elgin Crescent",
        zip: "W11 2JD",
        city: "London",
      },
    ],
    birthday: "1981-06-04",
    notes: "London pub-quiz league. Never bet against him on cricket.",
    folder: "friends",
  },
  {
    slug: "anna",
    first: "Anna",
    last: "Vikström",
    phones: [["+46 70 555 81 26", "private"]],
    emails: [["anna.vikstrom@example.com", "private"]],
    birthday: "1980-04-02",
    notes: "Book club, first Tuesday of the month. Her turn to host.",
    folder: "friends",
  },
  {
    slug: "fredrik",
    first: "Fredrik",
    last: "Lundahl",
    phones: [["+46 72 555 36 90", "private"]],
    emails: [["fredrik.lundahl@example.com", "private"]],
    birthday: "1982-01-15",
    notes: "Five-a-side Tuesdays. Organises the January ski trip.",
    folder: "friends",
  },
  {
    slug: "maja",
    first: "Maja",
    last: "Holmberg",
    phones: [["+46 73 555 47 33", "private"]],
    emails: [["maja.holmberg@example.com", "private"]],
    birthday: "1988-08-27",
    notes: "Sara's oldest friend. Allergic to nuts — remember dinners.",
    folder: "friends",
  },
  {
    slug: "simon",
    first: "Simon",
    last: "Wallin",
    phones: [["+46 70 555 52 84", "private"]],
    emails: [["simon.wallin@example.com", "private"]],
    birthday: "1983-12-19",
    dates: [["KTH graduation", "2009-06-05"]],
    notes: "Study group from KTH. Now lecturing in Linköping.",
    folder: "friends",
  },
  {
    slug: "nadia",
    first: "Nadia",
    last: "Rahimi",
    phones: [["+46 76 555 29 41", "private"]],
    emails: [["nadia.rahimi@example.com", "private"]],
    birthday: "1987-02-09",
    notes: "Met through Anna's book club. Architect — did our sketches.",
    folder: "friends",
  },
  {
    slug: "elena",
    first: "Elena",
    last: "Marchetti",
    phones: [["+39 02 5555 0192", "private"]],
    emails: [["elena.marchetti@example.com", "private"]],
    addresses: [{ label: "Home", city: "Milano" }],
    birthday: "1985-05-22",
    notes: "Milan. Knows every trattoria worth queueing for.",
    folder: "friends",
  },
  {
    slug: "kristoffer",
    first: "Kristoffer",
    last: "Nyman",
    phones: [["+46 70 555 73 58", "private"]],
    emails: [["kristoffer.nyman@example.com", "private"]],
    birthday: "1979-09-01",
    notes: "Sailing crew. Skipper of the Omega 36 — May to September.",
    folder: "friends",
  },
  {
    slug: "linda",
    first: "Linda",
    last: "Axelsson",
    phones: [["+46 73 555 15 07", "private"]],
    emails: [["linda.axelsson@example.com", "private"]],
    birthday: "1984-10-25",
    notes: "Neighbour from the old flat on Odengatan. Still does Fikas.",
    folder: "friends",
  },
  {
    slug: "par",
    first: "Pär",
    last: "Sundin",
    phones: [["+46 70 555 68 44", "private"]],
    birthday: "1972-03-12",
    notes: "Summer-house neighbour on Ljusterö. Has the good ladder.",
    folder: "friends",
  },
  {
    slug: "rebecka",
    first: "Rebecka",
    last: "Åström",
    phones: [["+46 72 555 91 16", "private"]],
    emails: [["rebecka.astrom@example.com", "private"]],
    birthday: "1989-07-07",
    notes: "Runs the Lidingöloppet group chat. Sunday long runs.",
    folder: "friends",
  },
  {
    slug: "yuki",
    first: "Yuki",
    last: "Sato",
    phones: [["+81 3-5555-0148", "private"]],
    emails: [["yuki.sato@example.com", "private"]],
    addresses: [{ label: "Home", city: "Tokyo" }],
    birthday: "1986-01-11",
    notes: "Hosted us in Tokyo 2019. Owes her a Stockholm itinerary.",
    folder: "friends",
  },
];

/** Acquaintances at the menu root — the cards that never quite need a folder. */
export const DEMO_ACQUAINTANCES: DemoContactSpec[] = [
  {
    slug: "gustav",
    first: "Gustav",
    last: "Åhlén",
    phones: [["+46 70 555 40 92", "private"]],
    notes: "Met at Fredrik's 40th. Beekeeper — honey around September.",
  },
  {
    slug: "cecilia",
    first: "Cecilia",
    last: "Brandt",
    company: "Brandt & Partners Fastighetsbyrå",
    phones: [["+46 70 555 62 15", "work"]],
    emails: [["cecilia@brandtpartners.example", "work"]],
    homepage: "https://www.brandtpartners.example",
    notes: "Estate agent — sold us the house 2019. Valuation every spring.",
    glyph: "briefcase",
    color: "#fcd34d",
  },
  {
    slug: "tove",
    first: "Tove",
    last: "Nilsén",
    phones: [["+46 76 555 84 03", "private"]],
    emails: [["tove.nilsen@example.com", "private"]],
    notes: "Dog sitter for Milo. Recommended by Petra. 250 kr/day.",
    glyph: "person",
    color: "#86efac",
  },
  {
    slug: "ricardo",
    first: "Ricardo",
    last: "Álvarez",
    phones: [["+34 91 555 02 76", "private"]],
    emails: [["ricardo.alvarez@example.com", "private"]],
    addresses: [{ label: "Home", city: "Sevilla" }],
    notes: "Our Seville host, Easter 2025. Said to call next time.",
  },
  {
    slug: "kerstin",
    first: "Kerstin",
    last: "Vall",
    phones: [["+46 70 555 19 38", "private"]],
    notes: "Piano tuner — comes every November. Book in October.",
    glyph: "music",
    color: "#c4b5fd",
  },
  {
    slug: "niklas",
    first: "Niklas",
    last: "Ehn",
    phones: [["+46 72 555 07 61", "private"]],
    notes: "Bought the kayak from him, spring 2024. Kept the receipt.",
  },
  {
    slug: "amir",
    first: "Amir",
    last: "Karimi",
    phones: [["+46 73 555 30 22", "private"]],
    emails: [["amir.karimi@example.com", "private"]],
    notes: "Elsa's maths tutor. Wednesdays 16:30, online.",
    glyph: "book",
    color: "#93c5fd",
  },
  {
    slug: "helen",
    first: "Helen",
    last: "Marsh",
    phones: [["+44 20 7946 0523", "private"]],
    emails: [["helen.marsh@example.com", "private"]],
    addresses: [{ label: "Fell View B&B", city: "Keswick" }],
    notes: "B&B host, Lake District 2023. Ask for the corner room.",
  },
  {
    slug: "ola",
    first: "Ola",
    last: "Rydberg",
    phones: [["+46 70 555 95 47", "private"]],
    emails: [["ola.rydberg@example.com", "private"]],
    notes: "Allotment association contact. Water rota in the summer.",
    glyph: "leaf",
    color: "#86efac",
  },
  {
    slug: "sanna",
    first: "Sanna",
    last: "Modin",
    phones: [["+46 76 555 12 89", "private"]],
    notes: "Yoga, Wednesday 18:00 class. Pays by Swish per term.",
  },
  {
    slug: "georg",
    first: "Georg",
    last: "Papadopoulos",
    company: "Taverna Meltemi",
    phones: [["+30 21 0555 0134", "work"]],
    addresses: [{ label: "Taverna", city: "Naxos" }],
    notes: "Naxos 2024. Book the seafront table a day ahead in July.",
    glyph: "utensils",
    color: "#fdba74",
  },
  {
    slug: "milena",
    first: "Milena",
    last: "Novák",
    phones: [["+420 601 555 213", "work"]],
    emails: [["milena.novak@example.com", "work"]],
    notes: "Conference contact, Prague 2025. Follow up about the talk.",
  },
  {
    slug: "bjorn",
    first: "Björn",
    last: "Stigsson",
    phones: [["+46 70 555 56 71", "private"]],
    emails: [["bjorn.stigsson@example.com", "private"]],
    notes: "Scout leader — Oskar's troop. Kit list goes out in August.",
  },
];

/** Archived personal cards — kept, but out of the way. */
export const DEMO_ARCHIVED_PEOPLE: DemoContactSpec[] = [
  {
    slug: "rolf",
    first: "Rolf",
    last: "Ekberg",
    phones: [["+46 8 555 038 12", "private"]],
    notes: "Landlord at Odengatan. Moved out 2019 — deposit settled.",
    archived: true,
  },
  {
    slug: "margareta",
    first: "Margareta",
    last: "Björk",
    company: "Tandläkarpraktik M. Björk",
    phones: [["+46 8 555 041 55", "work"]],
    notes: "Old dentist — retired 2024. Records moved to Tandläkarhuset.",
    archived: true,
  },
  {
    slug: "casper",
    first: "Casper",
    last: "Weiland",
    phones: [["+46 70 555 88 60", "private"]],
    emails: [["casper.weiland@example.com", "private"]],
    notes: "Old tennis partner. Moved to Alicante — number may be stale.",
    archived: true,
  },
];
