// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// The professional half of the demo address book: colleagues at the owner's
// employer (Klarvik Systems), the client contacts filed in a subfolder under
// Work, and the previous employer's people — a whole folder realistically
// archived when the owner changed jobs. See `demoData.ts` for the roster
// overview and `demoSpec.ts` for the authoring shape.

import type { DemoContactSpec } from "./demoSpec.ts";

/** Work — the day-to-day colleagues, plus the employer's own switchboard card. */
export const DEMO_WORK: DemoContactSpec[] = [
  // The boss: a favorite — she's called often enough to earn the shortlist.
  {
    slug: "katarina",
    first: "Katarina",
    last: "Wennerström",
    company: "Klarvik Systems AB",
    phones: [
      ["+46 70 555 03 17", "work", "primary"],
      ["+46 8 555 016 02", "work"],
    ],
    emails: [["katarina.wennerstrom@klarvik.example", "work"]],
    birthday: "1975-06-18",
    notes: "CTO. Prefers a call over a long email thread.",
    folder: "work",
    favorite: 4,
  },
  {
    slug: "ali",
    first: "Ali",
    last: "Hassan",
    company: "Klarvik Systems AB",
    phones: [["+46 72 555 03 21", "work"]],
    emails: [["ali.hassan@klarvik.example", "work"]],
    birthday: "1991-08-05",
    notes: "Backend team. Carpool partner on office Tuesdays.",
    folder: "work",
  },
  {
    slug: "josefin",
    first: "Josefin",
    last: "Ek",
    company: "Klarvik Systems AB",
    phones: [["+46 73 555 03 24", "work"]],
    emails: [["josefin.ek@klarvik.example", "work"]],
    birthday: "1988-02-28",
    notes: "Runs the platform team. On-call rota owner.",
    folder: "work",
  },
  {
    slug: "mattias",
    first: "Mattias",
    last: "Berg",
    company: "Klarvik Systems AB",
    phones: [["+46 70 555 03 29", "work"]],
    emails: [["mattias.berg@klarvik.example", "work"]],
    birthday: "1986-12-03",
    notes: "Desk neighbour. Collects for Friday breakfast.",
    folder: "work",
  },
  {
    slug: "priya",
    first: "Priya",
    last: "Nair",
    company: "Klarvik Systems AB",
    phones: [["+46 76 555 03 33", "work"]],
    emails: [["priya.nair@klarvik.example", "work"]],
    birthday: "1993-04-19",
    notes: "Design lead. Book her early for review weeks.",
    folder: "work",
  },
  {
    slug: "stefan",
    first: "Stefan",
    last: "Hjelm",
    company: "Klarvik Systems AB",
    phones: [["+46 70 555 03 40", "work"]],
    emails: [["stefan.hjelm@klarvik.example", "work"]],
    notes: "Sales. Loops me in on technical pre-studies.",
    folder: "work",
  },
  {
    slug: "camilla",
    first: "Camilla",
    last: "Sjögren",
    company: "Klarvik Systems AB",
    phones: [["+46 8 555 016 15", "work"]],
    emails: [["camilla.sjogren@klarvik.example", "work"]],
    notes: "HR — payroll and parental-leave questions.",
    folder: "work",
  },
  {
    slug: "robert",
    first: "Robert",
    last: "Lindell",
    company: "Klarvik Systems AB",
    phones: [["+46 8 555 016 40", "work"]],
    emails: [["helpdesk@klarvik.example", "work"]],
    notes: "IT helpdesk. Extension 402 for laptop trouble.",
    folder: "work",
  },
  {
    slug: "sofia-g",
    first: "Sofia",
    last: "Grankvist",
    company: "Klarvik Systems AB",
    phones: [["+46 73 555 03 44", "work"]],
    emails: [["sofia.grankvist@klarvik.example", "work"]],
    notes: "Finance. Expense reports before the 25th.",
    folder: "work",
  },
  {
    slug: "daniel",
    first: "Daniel",
    last: "Roos",
    company: "Klarvik Systems AB",
    phones: [["+46 70 555 03 48", "work"]],
    emails: [["daniel.roos@klarvik.example", "work"]],
    birthday: "1990-09-26",
    notes: "Moved to the Göteborg office 2025. Still owns the wiki.",
    folder: "work",
  },
  {
    slug: "marta",
    first: "Marta",
    last: "Kowalczyk",
    company: "Klarvik Systems AB",
    phones: [["+48 22 555 01 62", "work"]],
    emails: [["marta.kowalczyk@klarvik.example", "work"]],
    addresses: [{ label: "Office", city: "Warszawa" }],
    notes: "Warsaw office lead. One hour behind — book meetings late.",
    folder: "work",
  },
  // The employer itself — switchboard, address, the card you give a courier.
  {
    slug: "klarvik",
    company: "Klarvik Systems AB",
    isCompany: true,
    homepage: "https://www.klarvik.example",
    phones: [["+46 8 555 016 00", "work"]],
    emails: [["info@klarvik.example", "work"]],
    addresses: [
      {
        label: "Office",
        street: "Vasagatan 28",
        zip: "111 20",
        city: "Stockholm",
      },
    ],
    notes: "Switchboard. Visitor entrance on Klara Norra kyrkogata.",
    folder: "work",
    glyph: "building",
    color: "#93c5fd",
  },
];

/** Clients — the external people (and their companies) under Work ▸ Clients. */
export const DEMO_CLIENTS: DemoContactSpec[] = [
  {
    slug: "john",
    first: "John",
    last: "Appleseed",
    company: "Meridian Software Inc.",
    phones: [
      ["+1 (408) 555-0125", "work", "primary"],
      ["+1 (408) 555-0108", "private"],
    ],
    emails: [["john.appleseed@meridiansoftware.example", "work"]],
    birthday: "1980-06-01",
    notes: "Platform lead at Meridian. Met at the Austin conference 2024.",
    folder: "clients",
  },
  {
    slug: "meridian",
    company: "Meridian Software Inc.",
    isCompany: true,
    homepage: "https://www.meridiansoftware.example",
    phones: [["+1 (408) 555-0100", "work"]],
    emails: [["hello@meridiansoftware.example", "work"]],
    addresses: [
      {
        label: "HQ",
        street: "1 Infinite Meadow Dr",
        zip: "95014",
        city: "Cupertino",
      },
    ],
    notes: "Contract renewal every March. NDA on file.",
    folder: "clients",
    glyph: "building",
    color: "#5eead4",
  },
  {
    slug: "birgitta",
    first: "Birgitta",
    last: "Fors",
    company: "Trygghem Försäkring AB",
    phones: [["+46 70 555 47 80", "work"]],
    emails: [["birgitta.fors@trygghem.example", "work"]],
    notes: "Project owner on the claims-portal rebuild. Fridays off.",
    folder: "clients",
  },
  {
    slug: "trygghem",
    company: "Trygghem Försäkring AB",
    isCompany: true,
    homepage: "https://www.trygghem.example",
    phones: [["+46 8 555 028 00", "work"]],
    addresses: [
      {
        label: "Office",
        street: "Sveavägen 110",
        zip: "113 50",
        city: "Stockholm",
      },
    ],
    notes: "Client since 2023. Invoices via their supplier portal.",
    folder: "clients",
    glyph: "landmark",
    color: "#fcd34d",
  },
  {
    slug: "oliver",
    first: "Oliver",
    last: "Bennett",
    company: "Harwick & Dune Ltd",
    phones: [["+44 20 7946 0230", "work"]],
    emails: [["oliver.bennett@harwickdune.example", "work"]],
    addresses: [{ label: "Office", city: "London" }],
    notes: "London retainer. Quarterly review calls, GMT mornings.",
    folder: "clients",
  },
  {
    slug: "hanne",
    first: "Hanne",
    last: "Kristiansen",
    company: "Fjordkraft Digital AS",
    phones: [["+47 21 55 50 18", "work"]],
    emails: [["hanne.kristiansen@fjordkraftdigital.example", "work"]],
    notes: "Oslo pilot project. Prefers Teams over phone.",
    folder: "clients",
  },
  {
    slug: "lauri",
    first: "Lauri",
    last: "Mäkinen",
    company: "Kuusela Systems Oy",
    phones: [["+358 9 5555 0147", "work"]],
    emails: [["lauri.makinen@kuusela.example", "work"]],
    notes: "Helsinki integration partner. Sauna diplomacy works.",
    folder: "clients",
  },
  {
    slug: "isabelle",
    first: "Isabelle",
    last: "Moreau",
    company: "Atelier Numérique SARL",
    phones: [["+33 1 99 00 52 30", "work"]],
    emails: [["isabelle.moreau@ateliernumerique.example", "work"]],
    addresses: [{ label: "Office", city: "Paris" }],
    notes: "Paris agency we subcontract design to. August is sacred.",
    folder: "clients",
  },
];

/** The previous employer — a folder archived wholesale on the last day. */
export const DEMO_OLD_JOB: DemoContactSpec[] = [
  {
    slug: "torbjorn",
    first: "Torbjörn",
    last: "Wiklund",
    company: "Nordvik Consulting AB",
    phones: [["+46 70 555 71 20", "work"]],
    emails: [["torbjorn.wiklund@nordvik.example", "work"]],
    notes: "Old boss at Nordvik. Reference — cleared it with him 2022.",
    folder: "oldjob",
    archived: true,
  },
  {
    slug: "annika",
    first: "Annika",
    last: "Modig",
    company: "Nordvik Consulting AB",
    phones: [["+46 73 555 71 24", "work"]],
    emails: [["annika.modig@nordvik.example", "work"]],
    notes: "Nordvik project manager. Still meets the old team yearly.",
    folder: "oldjob",
    archived: true,
  },
  {
    slug: "jens",
    first: "Jens",
    last: "Petersen",
    company: "Nordvik Consulting AB",
    phones: [["+45 32 55 50 71", "work"]],
    emails: [["jens.petersen@nordvik.example", "work"]],
    notes: "Copenhagen office. Hosted the 2021 kick-off.",
    folder: "oldjob",
    archived: true,
  },
  {
    slug: "nordvik",
    company: "Nordvik Consulting AB",
    isCompany: true,
    homepage: "https://www.nordvik.example",
    phones: [["+46 8 555 071 00", "work"]],
    notes: "Employer 2017–2022. HR keeps the pension paperwork.",
    folder: "oldjob",
    glyph: "building",
    color: "#c4b5fd",
    archived: true,
  },
];
